### ISSUE TITLE
Custom dimension warppad

### ISSUE THREAD

**Issue by NinjaGmBh** [SmoochyPit/Warp-Pads-Rewrite#1]
First of, i love this datapack you made. I am trying to make warppads in a custom dimension/world that is connected to my main world using the multiverse plugin. Problem is that when i create the warppads, they show the normal particle effects but not the ones for the other warppad. I think this might be cause the multiverse world is considered a custom dimension. Sadly i have never used trident before and am not entirely sure what to do. So if its not too much to ask, would it be possible for you to give me a short explanation on what i would have to do to make this work.

**Comment by SmoochyPit** [comment]
This project isn't coded to enable warping between multiple dimensions, though it's technically possible. However, I think multiworld plugins like that (at least in the past) don't use custom dimensions. Instead, they connect the player to a separate "sub-server", which is inaccessible through Vanilla commands. I know there's custom portal plug-ins that let you link between worlds, but I'm not aware of any with a holographic UI like this project has.

If you're sure they are all accessible in your world as custom dimensions (`/execute in [dimension]`), then you could fork this repo and modify the code. The dimension checks are in `warppad:logic/array_check` and `warppad:logic/conditions`. If you're only using Warp Pads for this specific purpose, it may be easiest to remove any checks for dimensions (along with the for loops nested around them.) The readme has a section labeled "configuration" that can show you how to set up and compile with Trident-UI. When you install [git](https://git-scm.com/) on Windows, you have the option to install "git bash" as well. I recommend using that terminal to run the commands in the readme if you choose to do this. 

If you're interested and need a hand with this, feel free to add me on discord: @SmoochyPit#8036. It'd be a great learning opportunity :).
