### ISSUE TITLE
Particles not working in 1.20.5

### ISSUE THREAD

**Issue by chrisdclary** [SmoochyPit/Warp-Pads-Rewrite#13]
Hey! Great data pack, it's super useful and I've been using it on my server for about a year now and loved it.
In 1.20.5 they updated a few things about particles, and I think that caused the color particles not to show up for the warp pads.
Warping still works fine, but you have to search around to find the spot where the warp name pops up

**Comment by SmoochyPit** [comment]
I'll get on this! Trident is no longer being maintained, but I think I can use the "verbatim commands" feature to fix this.

**Comment by SmoochyPit** [comment]
Fixed this in 961da4a6b2620e2d1b4377200adfbce5f5895063.

Unfortunately, I also found a whole slew of other bugs on 1.20.5+. I've began tracking all of them with #14. Thanks for letting me know about this issue so I could work towards mitigating it!
