### ISSUE TITLE
Tuning notification seems to be global

### ISSUE THREAD

**Issue by inventor200** [SmoochyPit/Warp-Pads-Rewrite#3]
This might have been fixed already (running 2.0b3 still), but if a player tunes their warppad, other players can sometimes see a message coming up saying "Warp pad frequency set to 2".

What's strange is that it only happens on frequency 2, and not for other ones.

**Comment by SmoochyPit** [comment]
I'll see if I can round up a friend to help me reproduce this behavior sometime. The message is supposed to only display to the thrower of the item, so I'm curious where that code targeted somebody else.

**Comment by SmoochyPit** [comment]
Unable to reproduce. Running v2.1.2 on Minecraft 1.19.

**Comment by SmoochyPit** [comment]
Reproduced by accident once, but can't consistently. I suspect changes made in commit 89255f1 will fix this issue.
