### ISSUE TITLE
Warp point disappears

### ISSUE THREAD

**Issue by da-jacob** [SmoochyPit/Warp-Pads-Rewrite#4]
I created 2 warp pads, one in my base and one in mines, the one in base works just fine, but the one in mines does not, it displays the circle around me, but the home point is there only for a split of a second and then it disappears

Seems like it has problem displaying points too far above. When I move the warp pad further away so the point is closer to the ground, then it's still visible

**Comment by SmoochyPit** [comment]
Able to reproduce with latest release using Minecraft 1.18.2. I'll get working on this-- warping up is pretty important.

**Comment by SmoochyPit** [comment]
Fixed in v2.1.1. Thanks!
