### ISSUE TITLE
Leaving a server during a cooldown bricks all warp pads.

### ISSUE THREAD

**Issue by IdeotikTable** [SmoochyPit/Warp-Pads-Rewrite#7]
As far as I know, this affects every player on the server, so no-one can use the warp pads, and I believe this hasn't been reported before, so this isn't a known issue. It also seems that restarting the server doesn't fix it. An easy recreation would be to join a server, place 2 warp pads, warp between them until you reach the cooldown, and leave the server. 

I feel like this is a simple but major issue, as it would only take one player to ruin an entire servers warp pad transport system, so I'm sure this could be a pretty important patch.

Forgot to mention this is the latest release (v2.1.1), tested on a Vanilla 1.19 server, hosted by Aternos.

**Comment by SmoochyPit** [comment]
Able to reproduce with latest version (v2.1.1) running Minecraft 1.18.2. Scheduled functions don't persist through restarts, so I'll have to add a check for timed-out players during load.

For now, running `/function warppad:logic/warping/tick_cool_down` will reengage the timer and fix this if it occurs.

**Comment by SmoochyPit** [comment]
Fixed in v2.1.2. Thanks!
